debug: true
server:
  port: 8001
  servlet:
    context-path: /
     
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: 1711
    url: jdbc:postgresql://containers-us-west-51.railway.app:5864/railway
    username: postgres
    password: rEKAgdMCiSOVLdXePTcf
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  security:
    oauth2:
      client:
        registration:
         facebook:
          clientId: 6631759010176516
          clientSecret: bbec179ecd337a11662ad0fa3f5c4caf
          scope:
           - email
           - public_profile
          redirect-uri: https://login-test-prod.up.railway.app/login/oauth2/code/facebook
         google:
           clientId: 869020242992-d6p3nh9rte50gr1u6jb96qquqndvfq9l.apps.googleusercontent.com
           clientSecret: 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
           scope:
             - email
             - profile
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: INFO